export type TranslationMap = Record<string, string>;

const en: TranslationMap = {
  "Listor":"Lists", "Användare & grupper":"Users & groups", "Statistik":"Statistics", "Inställningar":"Settings",
  "Stöd Bubbsun":"Support Bubbsun", "Om":"About", "Hjälp":"Help", "Mina listor":"My lists", "Grupper":"Groups",
  "Lägg till":"Add", "Lägg till produkt":"Add", "Namn":"Name", "Mängd (valfritt)":"Quantity (optional)",
  "Sök i listan":"Search list", "Klart":"Completed", "Kvar":"Remaining", "Klara":"Completed", "Redigera":"Edit",
  "Redigera lista":"Edit list", "Ta bort":"Delete", "Radera":"Delete", "Följ lista":"Follow list",
  "Sluta följa lista":"Unfollow list", "Ta bort poster":"Delete items", "Välj färg":"Choose color", "Välj ikon":"Choose icon",
  "Avbryt":"Cancel", "Spara":"Save", "Skapa grupp":"Create group", "Gå med":"Join", "Medlemmar":"Members",
  "Mina grupper":"My groups", "Teman":"Themes", "Tema":"Theme", "Språk":"Language", "Mer":"More",
  "Hjälp & guider":"Help & guides", "Integritet & molndata":"Privacy & cloud data", "Versioner & nyheter":"Versions & news",
  "Rapportera problem":"Report a problem", "Skicka förslag":"Send suggestion", "Logga ut":"Sign out", "Alla användare":"All users",
  "Buggar & förslag":"Bugs & suggestions", "Typ":"Type", "Rubrik":"Subject", "Beskriv så tydligt du kan…":"Describe as clearly as you can…",
  "Få information när listan ändras":"Get notified when the list changes", "Ändra listans namn och inställningar":"Change the list name and settings",
  "Markera flera poster samtidigt":"Select several items at once", "Om Bubbsun":"About Bubbsun", "Supporterinställningar":"Supporter settings",
  "Öppna meny":"Open menu", "Gå till Mina listor":"Go to My lists", "Skapa en lista":"Create a list", "Hantera listan":"Manage list",
  "Stäng":"Close", "Färdig":"Done", "Välj tema":"Choose theme", "Min profil":"My profile", "Visningsnamn":"Display name",
  "Gruppkod":"Group code", "Mina privata listor":"My private lists", "Bara du kan se dem":"Only you can see them"
  ,"Supporter, Facebook och Bubbsun":"Supporter, Facebook and Bubbsun", "Bli en del av Bubbsun-hjärtat":"Become part of the Bubbsun heart",
  "Hjälp Bubbsun att fortsätta växa.":"Help Bubbsun keep growing.", "Du hjälper Bubbsun att leva vidare, utvecklas och hålla familjens listor synkade. Tack för att du gör allt detta möjligt.":"You help Bubbsun live on, grow and keep the family's lists in sync. Thank you for making it possible.",
  "Aktivera gratis supporter":"Activate free supporter", "Välj dekorationen som visas vid Bubbsun-loggan.":"Choose the decoration shown by the Bubbsun logo.",
  "Fancy Glow":"Fancy Glow", "Mjukt sken runt Bubbsun-loggan.":"Soft glow around the Bubbsun logo.", "Kosmiskt, Hjärtligt och Gotiskt tema":"Cosmic, Heart and Gothic themes",
  "Exklusiva listikoner och färger":"Exclusive list icons and colours", "Supportertitel vid Bubbsun-loggan":"Supporter title by the Bubbsun logo", "Fancy Glow runt loggan":"Fancy Glow around the logo", "Founding Supporter-märke":"Founding Supporter badge"
};

const fi: TranslationMap = {"Listor":"Listat","Användare & grupper":"Käyttäjät ja ryhmät","Statistik":"Tilastot","Inställningar":"Asetukset","Stöd Bubbsun":"Tue Bubbsunia","Om":"Tietoja","Hjälp":"Ohje","Mina listor":"Omat listat","Grupper":"Ryhmät","Lägg till":"Lisää","Namn":"Nimi","Mängd (valfritt)":"Määrä (valinnainen)","Sök i listan":"Hae listasta","Klart":"Valmiit","Kvar":"Jäljellä","Klara":"Valmiit","Redigera":"Muokkaa","Redigera lista":"Muokkaa listaa","Ta bort":"Poista","Följ lista":"Seuraa listaa","Sluta följa lista":"Lopeta seuraaminen","Ta bort poster":"Poista kohteita","Välj färg":"Valitse väri","Välj ikon":"Valitse kuvake","Avbryt":"Peruuta","Spara":"Tallenna","Språk":"Kieli","Tema":"Teema","Logga ut":"Kirjaudu ulos"};
const de: TranslationMap = {"Listor":"Listen","Användare & grupper":"Benutzer & Gruppen","Statistik":"Statistik","Inställningar":"Einstellungen","Stöd Bubbsun":"Bubbsun unterstützen","Om":"Über","Hjälp":"Hilfe","Mina listor":"Meine Listen","Grupper":"Gruppen","Lägg till":"Hinzufügen","Namn":"Name","Mängd (valfritt)":"Menge (optional)","Sök i listan":"Liste durchsuchen","Klart":"Erledigt","Kvar":"Übrig","Klara":"Erledigt","Redigera":"Bearbeiten","Redigera lista":"Liste bearbeiten","Ta bort":"Löschen","Följ lista":"Liste folgen","Ta bort poster":"Einträge löschen","Välj färg":"Farbe wählen","Välj ikon":"Symbol wählen","Avbryt":"Abbrechen","Spara":"Speichern","Språk":"Sprache","Tema":"Thema","Logga ut":"Abmelden"};
const es: TranslationMap = {"Listor":"Listas","Användare & grupper":"Usuarios y grupos","Statistik":"Estadísticas","Inställningar":"Ajustes","Stöd Bubbsun":"Apoya a Bubbsun","Om":"Acerca de","Hjälp":"Ayuda","Mina listor":"Mis listas","Grupper":"Grupos","Lägg till":"Añadir","Namn":"Nombre","Mängd (valfritt)":"Cantidad (opcional)","Sök i listan":"Buscar en la lista","Klart":"Completado","Kvar":"Pendientes","Klara":"Completados","Redigera":"Editar","Redigera lista":"Editar lista","Ta bort":"Eliminar","Följ lista":"Seguir lista","Ta bort poster":"Eliminar elementos","Välj färg":"Elegir color","Välj ikon":"Elegir icono","Avbryt":"Cancelar","Spara":"Guardar","Språk":"Idioma","Tema":"Tema","Logga ut":"Cerrar sesión"};
const fr: TranslationMap = {"Listor":"Listes","Användare & grupper":"Utilisateurs et groupes","Statistik":"Statistiques","Inställningar":"Paramètres","Stöd Bubbsun":"Soutenir Bubbsun","Om":"À propos","Hjälp":"Aide","Mina listor":"Mes listes","Grupper":"Groupes","Lägg till":"Ajouter","Namn":"Nom","Mängd (valfritt)":"Quantité (facultatif)","Sök i listan":"Rechercher dans la liste","Klart":"Terminé","Kvar":"Restants","Klara":"Terminés","Redigera":"Modifier","Redigera lista":"Modifier la liste","Ta bort":"Supprimer","Följ lista":"Suivre la liste","Ta bort poster":"Supprimer des éléments","Välj färg":"Choisir la couleur","Välj ikon":"Choisir l’icône","Avbryt":"Annuler","Spara":"Enregistrer","Språk":"Langue","Tema":"Thème","Logga ut":"Se déconnecter"};
const it: TranslationMap = {"Listor":"Liste","Användare & grupper":"Utenti e gruppi","Statistik":"Statistiche","Inställningar":"Impostazioni","Stöd Bubbsun":"Sostieni Bubbsun","Om":"Informazioni","Hjälp":"Aiuto","Mina listor":"Le mie liste","Grupper":"Gruppi","Lägg till":"Aggiungi","Namn":"Nome","Mängd (valfritt)":"Quantità (facoltativa)","Sök i listan":"Cerca nella lista","Klart":"Completato","Kvar":"Rimanenti","Klara":"Completati","Redigera":"Modifica","Redigera lista":"Modifica lista","Ta bort":"Elimina","Följ lista":"Segui lista","Ta bort poster":"Elimina elementi","Välj färg":"Scegli colore","Välj ikon":"Scegli icona","Avbryt":"Annulla","Spara":"Salva","Språk":"Lingua","Tema":"Tema","Logga ut":"Esci"};
const pl: TranslationMap = {"Listor":"Listy","Användare & grupper":"Użytkownicy i grupy","Statistik":"Statystyki","Inställningar":"Ustawienia","Stöd Bubbsun":"Wesprzyj Bubbsun","Om":"O aplikacji","Hjälp":"Pomoc","Mina listor":"Moje listy","Grupper":"Grupy","Lägg till":"Dodaj","Namn":"Nazwa","Mängd (valfritt)":"Ilość (opcjonalnie)","Sök i listan":"Szukaj na liście","Klart":"Ukończone","Kvar":"Pozostało","Klara":"Ukończone","Redigera":"Edytuj","Redigera lista":"Edytuj listę","Ta bort":"Usuń","Följ lista":"Obserwuj listę","Ta bort poster":"Usuń pozycje","Välj färg":"Wybierz kolor","Välj ikon":"Wybierz ikonę","Avbryt":"Anuluj","Spara":"Zapisz","Språk":"Język","Tema":"Motyw","Logga ut":"Wyloguj"};
const nl: TranslationMap = {"Listor":"Lijsten","Användare & grupper":"Gebruikers en groepen","Statistik":"Statistieken","Inställningar":"Instellingen","Stöd Bubbsun":"Steun Bubbsun","Om":"Over","Hjälp":"Hulp","Mina listor":"Mijn lijsten","Grupper":"Groepen","Lägg till":"Toevoegen","Namn":"Naam","Mängd (valfritt)":"Aantal (optioneel)","Sök i listan":"Zoeken in lijst","Klart":"Voltooid","Kvar":"Resterend","Klara":"Voltooid","Redigera":"Bewerken","Redigera lista":"Lijst bewerken","Ta bort":"Verwijderen","Följ lista":"Lijst volgen","Ta bort poster":"Items verwijderen","Välj färg":"Kies kleur","Välj ikon":"Kies pictogram","Avbryt":"Annuleren","Spara":"Opslaan","Språk":"Taal","Tema":"Thema","Logga ut":"Uitloggen"};

Object.assign(en, {
  "Ny grupplista":"New group list", "Ny privat lista":"New private list", "Skriv listans namn":"Enter list name",
  "Ta bort hela listan":"Delete entire list", "Markera alla":"Select all", "Valda":"Selected", "Ta bort valda":"Delete selected",
  "Hantera medlem":"Manage member", "Gör till":"Make", "Gör till boss":"Make boss", "Gör till medlem":"Make member", "Gör till owner":"Make owner",
  "Redigera min profil":"Edit my profile", "Min färg":"My colour", "Redigera grupp":"Edit group", "Gruppfärg":"Group colour", "Gruppikon":"Group icon",
  "Poster":"Items", "Klara poster":"Completed items", "Eldar":"Flames", "Kvar just nu":"Remaining now", "Poster per lista":"Items per list", "Tomma listor":"Empty lists", "Med mängd":"With quantity",
  "Klart i procent":"Completion percentage", "Mest använda lista":"Most used list", "Aktiva i gruppen":"Active in the group", "Familjemedlemmar":"Family members", "Flest avbockningar":"Most completions",
  "Ingen ännu":"None yet", "Riktigt listproffs!":"A true list pro!", "Bra fart i listorna!":"Great progress on the lists!", "Allt börjar med en post.":"Everything starts with one item.", "Här finns plats för de första tummarna.":"There is room for the first flames here.",
  "Webbappens inställningar":"Web app settings", "Version, skapare och kontakt":"Version, creators and contact", "Utveckling & design":"Development & design", "Idéer, testning & feedback":"Ideas, testing & feedback", "Support & kvalitetskontroll":"Support & quality control",
  "Listor med hjärta":"Lists with heart", "Bubbsun föddes ur vardagens små listor – och växte till en varm plats där familjen kan hjälpas åt, minnas mer och glömma mindre.":"Bubbsun grew from everyday little lists into a warm place where families can help each other, remember more and forget less.", "Enkelt. Personligt. Tillsammans.":"Simple. Personal. Together.",
  "Hjälp oss förbättra Bubbsun":"Help us improve Bubbsun", "Skicka":"Send", "Krasch":"Crash", "Något fungerar inte":"Something is not working", "Utseende/layout":"Appearance/layout", "Tema/supporter":"Theme/supporter", "Uppdatering/installation":"Update/installation", "Annat":"Other", "Ny funktion":"New feature", "Design":"Design", "Ikoner/färger":"Icons/colours",
  "Tack för att du är du! 💗":"Thank you for being you! 💗", "Ditt stöd betyder mer än du anar.":"Your support means more than you know.", "♥ Du är bäst ♥":"♥ You are the best ♥",
  "Ljus retro":"Light retro", "Hav":"Ocean", "Skog":"Forest", "Solnedgång":"Sunset", "Vinter":"Winter", "Blomster":"Floral", "Eld":"Fire", "Kosmisk supporter":"Cosmic supporter", "Hjärtlig supporter":"Heart supporter", "Gotisk supporter":"Gothic supporter"
  , "Från Bubbsun":"From Bubbsun", "Röst":"Vote", "Röster":"Votes", "tryck för att öppna":"tap to open", "Göm för mig":"Hide for me", "Vill du dölja detta meddelande? Det visas igen nästa gång Bubbsun publicerar en ny version.":"Hide this message? It will appear again when Bubbsun publishes a new version."
});

export const uiTranslations: Record<string, TranslationMap> = { en, fi, de, es, fr, it, pl, nl, tlh: en };
